id: Gmail Account Setup

info:
  package_name: com.google.android.gm
  description: Setup a Google account on Gmail

inputs:
  - id: email-address
    description: Email address
  - id: password
    description: Password
